reportes_inicio:
    path:     /rpt
    defaults: { _controller: "GestionBundle:Pedidos:rptinicio" }
    methods:  [GET, POST]
reportes_pedidos:
    path:     /rptpedido
    defaults: { _controller: "GestionBundle:Pedidos:rptpedido" }
    methods:  [GET, POST]
filtros_rptped:
    path:     /fltrptped
    defaults: { _controller: "GestionBundle:Pedidos:filtroped" }
    methods:  [GET, POST]
sql_ped:
    path:     /sqlpd/{cliente2}/{cuenta2}/{hasta2}/{desde2}/{cliente}/{cuenta}/{hasta}/{desde}/{filtro1}/{filtro2}/{filtro3}/{filtro4}/{filtro5}/{filtro6}
    defaults: { _controller: "GestionBundle:Pedidos:sqlped" }
    methods:  [GET, POST]
reporte_operaciones:
    path:     /rptoperaciones
    defaults: { _controller: "GestionBundle:Factura:reporteoperaciones" }
    methods:  [GET, POST]
filtros_rptoper:
    path:     /rptopefiltros
    defaults: { _controller: "GestionBundle:Factura:rptopiltro" }
    methods:  [GET, POST]
sql_rptoper:
    path:     /sqlop/{cliente2}/{cuenta2}/{hasta2}/{desde2}/{cliente}/{cuenta}/{hasta}/{desde}/{filtro1}/{filtro2}/{filtro3}/{filtro4}/{filtro5}/{filtro6}/{filtro7}/{filtro8}/{filtro9}
    defaults: { _controller: "GestionBundle:Factura:sqloper" }
    methods:  [GET, POST]
reportes_saldos:
    path:     /rptsaldos
    defaults: { _controller: "GestionBundle:Factura:rptsaldo" }
    methods:  [GET, POST]
filtros_rptsaldo:
    path:     /filtrosaldo
    defaults: { _controller: "GestionBundle:Factura:filtrosaldo" }
    methods:  [GET, POST]
sql_rptsaldo:
    path:     /sqlsaldo/{cliente}/{cuenta}/{fechahasta}/{fechadesde}/{tipofecha}
    defaults: { _controller: "GestionBundle:Factura:sqlsaldo" }
    methods:  [GET, POST]
imprimir_general:
    path:     /impr/{desde}/{hasta}/{cliente}/{cuenta}
    defaults: { _controller: "GestionBundle:Recolecciones:filtrogeneral" }
    methods:  [POST, GET]